/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.Rarity;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * ConsumableTierDefinition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class ConsumableTierDefinition {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_RARITY = "rarity";
  @SerializedName(SERIALIZED_NAME_RARITY)
  private Rarity rarity;

  public static final String SERIALIZED_NAME_NAME_KEY = "nameKey";
  @SerializedName(SERIALIZED_NAME_NAME_KEY)
  private String nameKey;

  public static final String SERIALIZED_NAME_ICON_KEY = "iconKey";
  @SerializedName(SERIALIZED_NAME_ICON_KEY)
  private String iconKey;

  public static final String SERIALIZED_NAME_EFFECT_ICON_FRAME_KEY = "effectIconFrameKey";
  @SerializedName(SERIALIZED_NAME_EFFECT_ICON_FRAME_KEY)
  private String effectIconFrameKey;

  public ConsumableTierDefinition() {
  }

  public ConsumableTierDefinition id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public ConsumableTierDefinition rarity(Rarity rarity) {
    this.rarity = rarity;
    return this;
  }

  /**
   * Get rarity
   * @return rarity
   */
  @javax.annotation.Nullable
  public Rarity getRarity() {
    return rarity;
  }

  public void setRarity(Rarity rarity) {
    this.rarity = rarity;
  }


  public ConsumableTierDefinition nameKey(String nameKey) {
    this.nameKey = nameKey;
    return this;
  }

  /**
   * Get nameKey
   * @return nameKey
   */
  @javax.annotation.Nullable
  public String getNameKey() {
    return nameKey;
  }

  public void setNameKey(String nameKey) {
    this.nameKey = nameKey;
  }


  public ConsumableTierDefinition iconKey(String iconKey) {
    this.iconKey = iconKey;
    return this;
  }

  /**
   * Get iconKey
   * @return iconKey
   */
  @javax.annotation.Nullable
  public String getIconKey() {
    return iconKey;
  }

  public void setIconKey(String iconKey) {
    this.iconKey = iconKey;
  }


  public ConsumableTierDefinition effectIconFrameKey(String effectIconFrameKey) {
    this.effectIconFrameKey = effectIconFrameKey;
    return this;
  }

  /**
   * Get effectIconFrameKey
   * @return effectIconFrameKey
   */
  @javax.annotation.Nullable
  public String getEffectIconFrameKey() {
    return effectIconFrameKey;
  }

  public void setEffectIconFrameKey(String effectIconFrameKey) {
    this.effectIconFrameKey = effectIconFrameKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumableTierDefinition consumableTierDefinition = (ConsumableTierDefinition) o;
    return Objects.equals(this.id, consumableTierDefinition.id) &&
        Objects.equals(this.rarity, consumableTierDefinition.rarity) &&
        Objects.equals(this.nameKey, consumableTierDefinition.nameKey) &&
        Objects.equals(this.iconKey, consumableTierDefinition.iconKey) &&
        Objects.equals(this.effectIconFrameKey, consumableTierDefinition.effectIconFrameKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rarity, nameKey, iconKey, effectIconFrameKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumableTierDefinition {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rarity: ").append(toIndentedString(rarity)).append("\n");
    sb.append("    nameKey: ").append(toIndentedString(nameKey)).append("\n");
    sb.append("    iconKey: ").append(toIndentedString(iconKey)).append("\n");
    sb.append("    effectIconFrameKey: ").append(toIndentedString(effectIconFrameKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("rarity");
    openapiFields.add("nameKey");
    openapiFields.add("iconKey");
    openapiFields.add("effectIconFrameKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsumableTierDefinition
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsumableTierDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsumableTierDefinition is not found in the empty JSON string", ConsumableTierDefinition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsumableTierDefinition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsumableTierDefinition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `rarity`
      if (jsonObj.get("rarity") != null && !jsonObj.get("rarity").isJsonNull()) {
        Rarity.validateJsonElement(jsonObj.get("rarity"));
      }
      if ((jsonObj.get("nameKey") != null && !jsonObj.get("nameKey").isJsonNull()) && !jsonObj.get("nameKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameKey").toString()));
      }
      if ((jsonObj.get("iconKey") != null && !jsonObj.get("iconKey").isJsonNull()) && !jsonObj.get("iconKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iconKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iconKey").toString()));
      }
      if ((jsonObj.get("effectIconFrameKey") != null && !jsonObj.get("effectIconFrameKey").isJsonNull()) && !jsonObj.get("effectIconFrameKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `effectIconFrameKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("effectIconFrameKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsumableTierDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsumableTierDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsumableTierDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsumableTierDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsumableTierDefinition>() {
           @Override
           public void write(JsonWriter out, ConsumableTierDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsumableTierDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsumableTierDefinition given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsumableTierDefinition
   * @throws IOException if the JSON string is invalid with respect to ConsumableTierDefinition
   */
  public static ConsumableTierDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsumableTierDefinition.class);
  }

  /**
   * Convert an instance of ConsumableTierDefinition to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

