/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * LeaderboardStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class LeaderboardStatus {
  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  private Integer rank;

  public static final String SERIALIZED_NAME_RANK_DELTA = "rankDelta";
  @SerializedName(SERIALIZED_NAME_RANK_DELTA)
  private Integer rankDelta;

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  private Integer score;

  public static final String SERIALIZED_NAME_SCORE_DELTA = "scoreDelta";
  @SerializedName(SERIALIZED_NAME_SCORE_DELTA)
  private Integer scoreDelta;

  public LeaderboardStatus() {
  }

  public LeaderboardStatus rank(Integer rank) {
    this.rank = rank;
    return this;
  }

  /**
   * Get rank
   * @return rank
   */
  @javax.annotation.Nullable
  public Integer getRank() {
    return rank;
  }

  public void setRank(Integer rank) {
    this.rank = rank;
  }


  public LeaderboardStatus rankDelta(Integer rankDelta) {
    this.rankDelta = rankDelta;
    return this;
  }

  /**
   * Get rankDelta
   * @return rankDelta
   */
  @javax.annotation.Nullable
  public Integer getRankDelta() {
    return rankDelta;
  }

  public void setRankDelta(Integer rankDelta) {
    this.rankDelta = rankDelta;
  }


  public LeaderboardStatus score(Integer score) {
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   */
  @javax.annotation.Nullable
  public Integer getScore() {
    return score;
  }

  public void setScore(Integer score) {
    this.score = score;
  }


  public LeaderboardStatus scoreDelta(Integer scoreDelta) {
    this.scoreDelta = scoreDelta;
    return this;
  }

  /**
   * Get scoreDelta
   * @return scoreDelta
   */
  @javax.annotation.Nullable
  public Integer getScoreDelta() {
    return scoreDelta;
  }

  public void setScoreDelta(Integer scoreDelta) {
    this.scoreDelta = scoreDelta;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeaderboardStatus leaderboardStatus = (LeaderboardStatus) o;
    return Objects.equals(this.rank, leaderboardStatus.rank) &&
        Objects.equals(this.rankDelta, leaderboardStatus.rankDelta) &&
        Objects.equals(this.score, leaderboardStatus.score) &&
        Objects.equals(this.scoreDelta, leaderboardStatus.scoreDelta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rank, rankDelta, score, scoreDelta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeaderboardStatus {\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    rankDelta: ").append(toIndentedString(rankDelta)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    scoreDelta: ").append(toIndentedString(scoreDelta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rank");
    openapiFields.add("rankDelta");
    openapiFields.add("score");
    openapiFields.add("scoreDelta");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LeaderboardStatus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LeaderboardStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LeaderboardStatus is not found in the empty JSON string", LeaderboardStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LeaderboardStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LeaderboardStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LeaderboardStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LeaderboardStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LeaderboardStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LeaderboardStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<LeaderboardStatus>() {
           @Override
           public void write(JsonWriter out, LeaderboardStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LeaderboardStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LeaderboardStatus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LeaderboardStatus
   * @throws IOException if the JSON string is invalid with respect to LeaderboardStatus
   */
  public static LeaderboardStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LeaderboardStatus.class);
  }

  /**
   * Convert an instance of LeaderboardStatus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

