/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.StatModSlot;
import io.github.doenisf.comlink4j.model.UnitStat;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * ModRecommendationPrimaryStat
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class ModRecommendationPrimaryStat {
  public static final String SERIALIZED_NAME_SLOT = "slot";
  @SerializedName(SERIALIZED_NAME_SLOT)
  private StatModSlot slot;

  public static final String SERIALIZED_NAME_STAT = "stat";
  @SerializedName(SERIALIZED_NAME_STAT)
  private List<UnitStat> stat = new ArrayList<>();

  public ModRecommendationPrimaryStat() {
  }

  public ModRecommendationPrimaryStat slot(StatModSlot slot) {
    this.slot = slot;
    return this;
  }

  /**
   * Get slot
   * @return slot
   */
  @javax.annotation.Nullable
  public StatModSlot getSlot() {
    return slot;
  }

  public void setSlot(StatModSlot slot) {
    this.slot = slot;
  }


  public ModRecommendationPrimaryStat stat(List<UnitStat> stat) {
    this.stat = stat;
    return this;
  }

  public ModRecommendationPrimaryStat addStatItem(UnitStat statItem) {
    if (this.stat == null) {
      this.stat = new ArrayList<>();
    }
    this.stat.add(statItem);
    return this;
  }

  /**
   * Get stat
   * @return stat
   */
  @javax.annotation.Nullable
  public List<UnitStat> getStat() {
    return stat;
  }

  public void setStat(List<UnitStat> stat) {
    this.stat = stat;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModRecommendationPrimaryStat modRecommendationPrimaryStat = (ModRecommendationPrimaryStat) o;
    return Objects.equals(this.slot, modRecommendationPrimaryStat.slot) &&
        Objects.equals(this.stat, modRecommendationPrimaryStat.stat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slot, stat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModRecommendationPrimaryStat {\n");
    sb.append("    slot: ").append(toIndentedString(slot)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("slot");
    openapiFields.add("stat");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModRecommendationPrimaryStat
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModRecommendationPrimaryStat.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModRecommendationPrimaryStat is not found in the empty JSON string", ModRecommendationPrimaryStat.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ModRecommendationPrimaryStat.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModRecommendationPrimaryStat` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `slot`
      if (jsonObj.get("slot") != null && !jsonObj.get("slot").isJsonNull()) {
        StatModSlot.validateJsonElement(jsonObj.get("slot"));
      }
      if (jsonObj.get("stat") != null && !jsonObj.get("stat").isJsonNull()) {
        JsonArray jsonArraystat = jsonObj.getAsJsonArray("stat");
        if (jsonArraystat != null) {
          // ensure the json data is an array
          if (!jsonObj.get("stat").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `stat` to be an array in the JSON string but got `%s`", jsonObj.get("stat").toString()));
          }

          // validate the optional field `stat` (array)
          for (int i = 0; i < jsonArraystat.size(); i++) {
            UnitStat.validateJsonElement(jsonArraystat.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModRecommendationPrimaryStat.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModRecommendationPrimaryStat' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModRecommendationPrimaryStat> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModRecommendationPrimaryStat.class));

       return (TypeAdapter<T>) new TypeAdapter<ModRecommendationPrimaryStat>() {
           @Override
           public void write(JsonWriter out, ModRecommendationPrimaryStat value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModRecommendationPrimaryStat read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModRecommendationPrimaryStat given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModRecommendationPrimaryStat
   * @throws IOException if the JSON string is invalid with respect to ModRecommendationPrimaryStat
   */
  public static ModRecommendationPrimaryStat fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModRecommendationPrimaryStat.class);
  }

  /**
   * Convert an instance of ModRecommendationPrimaryStat to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

