/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * RaidAbilityOverride
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class RaidAbilityOverride {
  public static final String SERIALIZED_NAME_ABILITY_ID = "abilityId";
  @SerializedName(SERIALIZED_NAME_ABILITY_ID)
  private String abilityId;

  public static final String SERIALIZED_NAME_TARGET_RULE_ID = "targetRuleId";
  @SerializedName(SERIALIZED_NAME_TARGET_RULE_ID)
  private String targetRuleId;

  public static final String SERIALIZED_NAME_LOC_KEY = "locKey";
  @SerializedName(SERIALIZED_NAME_LOC_KEY)
  private String locKey;

  public static final String SERIALIZED_NAME_ICON = "icon";
  @SerializedName(SERIALIZED_NAME_ICON)
  private String icon;

  public RaidAbilityOverride() {
  }

  public RaidAbilityOverride abilityId(String abilityId) {
    this.abilityId = abilityId;
    return this;
  }

  /**
   * Get abilityId
   * @return abilityId
   */
  @javax.annotation.Nullable
  public String getAbilityId() {
    return abilityId;
  }

  public void setAbilityId(String abilityId) {
    this.abilityId = abilityId;
  }


  public RaidAbilityOverride targetRuleId(String targetRuleId) {
    this.targetRuleId = targetRuleId;
    return this;
  }

  /**
   * Get targetRuleId
   * @return targetRuleId
   */
  @javax.annotation.Nullable
  public String getTargetRuleId() {
    return targetRuleId;
  }

  public void setTargetRuleId(String targetRuleId) {
    this.targetRuleId = targetRuleId;
  }


  public RaidAbilityOverride locKey(String locKey) {
    this.locKey = locKey;
    return this;
  }

  /**
   * Get locKey
   * @return locKey
   */
  @javax.annotation.Nullable
  public String getLocKey() {
    return locKey;
  }

  public void setLocKey(String locKey) {
    this.locKey = locKey;
  }


  public RaidAbilityOverride icon(String icon) {
    this.icon = icon;
    return this;
  }

  /**
   * Get icon
   * @return icon
   */
  @javax.annotation.Nullable
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaidAbilityOverride raidAbilityOverride = (RaidAbilityOverride) o;
    return Objects.equals(this.abilityId, raidAbilityOverride.abilityId) &&
        Objects.equals(this.targetRuleId, raidAbilityOverride.targetRuleId) &&
        Objects.equals(this.locKey, raidAbilityOverride.locKey) &&
        Objects.equals(this.icon, raidAbilityOverride.icon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abilityId, targetRuleId, locKey, icon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaidAbilityOverride {\n");
    sb.append("    abilityId: ").append(toIndentedString(abilityId)).append("\n");
    sb.append("    targetRuleId: ").append(toIndentedString(targetRuleId)).append("\n");
    sb.append("    locKey: ").append(toIndentedString(locKey)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("abilityId");
    openapiFields.add("targetRuleId");
    openapiFields.add("locKey");
    openapiFields.add("icon");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RaidAbilityOverride
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RaidAbilityOverride.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RaidAbilityOverride is not found in the empty JSON string", RaidAbilityOverride.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RaidAbilityOverride.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RaidAbilityOverride` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("abilityId") != null && !jsonObj.get("abilityId").isJsonNull()) && !jsonObj.get("abilityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `abilityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("abilityId").toString()));
      }
      if ((jsonObj.get("targetRuleId") != null && !jsonObj.get("targetRuleId").isJsonNull()) && !jsonObj.get("targetRuleId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetRuleId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetRuleId").toString()));
      }
      if ((jsonObj.get("locKey") != null && !jsonObj.get("locKey").isJsonNull()) && !jsonObj.get("locKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locKey").toString()));
      }
      if ((jsonObj.get("icon") != null && !jsonObj.get("icon").isJsonNull()) && !jsonObj.get("icon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `icon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("icon").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RaidAbilityOverride.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RaidAbilityOverride' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RaidAbilityOverride> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RaidAbilityOverride.class));

       return (TypeAdapter<T>) new TypeAdapter<RaidAbilityOverride>() {
           @Override
           public void write(JsonWriter out, RaidAbilityOverride value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RaidAbilityOverride read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RaidAbilityOverride given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RaidAbilityOverride
   * @throws IOException if the JSON string is invalid with respect to RaidAbilityOverride
   */
  public static RaidAbilityOverride fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RaidAbilityOverride.class);
  }

  /**
   * Convert an instance of RaidAbilityOverride to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

