/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.CombatType;
import io.github.doenisf.comlink4j.model.TerritoryRewardBracket;
import io.github.doenisf.comlink4j.model.TerritoryZoneDefinition;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * TerritoryTournamentConflictZoneDefinition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class TerritoryTournamentConflictZoneDefinition {
  public static final String SERIALIZED_NAME_COMBAT_TYPE = "combatType";
  @SerializedName(SERIALIZED_NAME_COMBAT_TYPE)
  private CombatType combatType;

  public static final String SERIALIZED_NAME_VICTORY_POINT_REWARDS = "victoryPointRewards";
  @SerializedName(SERIALIZED_NAME_VICTORY_POINT_REWARDS)
  private List<TerritoryRewardBracket> victoryPointRewards = new ArrayList<>();

  public static final String SERIALIZED_NAME_ZONE_DEFINITION = "zoneDefinition";
  @SerializedName(SERIALIZED_NAME_ZONE_DEFINITION)
  private TerritoryZoneDefinition zoneDefinition;

  public TerritoryTournamentConflictZoneDefinition() {
  }

  public TerritoryTournamentConflictZoneDefinition combatType(CombatType combatType) {
    this.combatType = combatType;
    return this;
  }

  /**
   * Get combatType
   * @return combatType
   */
  @javax.annotation.Nullable
  public CombatType getCombatType() {
    return combatType;
  }

  public void setCombatType(CombatType combatType) {
    this.combatType = combatType;
  }


  public TerritoryTournamentConflictZoneDefinition victoryPointRewards(List<TerritoryRewardBracket> victoryPointRewards) {
    this.victoryPointRewards = victoryPointRewards;
    return this;
  }

  public TerritoryTournamentConflictZoneDefinition addVictoryPointRewardsItem(TerritoryRewardBracket victoryPointRewardsItem) {
    if (this.victoryPointRewards == null) {
      this.victoryPointRewards = new ArrayList<>();
    }
    this.victoryPointRewards.add(victoryPointRewardsItem);
    return this;
  }

  /**
   * Get victoryPointRewards
   * @return victoryPointRewards
   */
  @javax.annotation.Nullable
  public List<TerritoryRewardBracket> getVictoryPointRewards() {
    return victoryPointRewards;
  }

  public void setVictoryPointRewards(List<TerritoryRewardBracket> victoryPointRewards) {
    this.victoryPointRewards = victoryPointRewards;
  }


  public TerritoryTournamentConflictZoneDefinition zoneDefinition(TerritoryZoneDefinition zoneDefinition) {
    this.zoneDefinition = zoneDefinition;
    return this;
  }

  /**
   * Get zoneDefinition
   * @return zoneDefinition
   */
  @javax.annotation.Nullable
  public TerritoryZoneDefinition getZoneDefinition() {
    return zoneDefinition;
  }

  public void setZoneDefinition(TerritoryZoneDefinition zoneDefinition) {
    this.zoneDefinition = zoneDefinition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerritoryTournamentConflictZoneDefinition territoryTournamentConflictZoneDefinition = (TerritoryTournamentConflictZoneDefinition) o;
    return Objects.equals(this.combatType, territoryTournamentConflictZoneDefinition.combatType) &&
        Objects.equals(this.victoryPointRewards, territoryTournamentConflictZoneDefinition.victoryPointRewards) &&
        Objects.equals(this.zoneDefinition, territoryTournamentConflictZoneDefinition.zoneDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(combatType, victoryPointRewards, zoneDefinition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerritoryTournamentConflictZoneDefinition {\n");
    sb.append("    combatType: ").append(toIndentedString(combatType)).append("\n");
    sb.append("    victoryPointRewards: ").append(toIndentedString(victoryPointRewards)).append("\n");
    sb.append("    zoneDefinition: ").append(toIndentedString(zoneDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("combatType");
    openapiFields.add("victoryPointRewards");
    openapiFields.add("zoneDefinition");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TerritoryTournamentConflictZoneDefinition
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TerritoryTournamentConflictZoneDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TerritoryTournamentConflictZoneDefinition is not found in the empty JSON string", TerritoryTournamentConflictZoneDefinition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TerritoryTournamentConflictZoneDefinition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TerritoryTournamentConflictZoneDefinition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `combatType`
      if (jsonObj.get("combatType") != null && !jsonObj.get("combatType").isJsonNull()) {
        CombatType.validateJsonElement(jsonObj.get("combatType"));
      }
      if (jsonObj.get("victoryPointRewards") != null && !jsonObj.get("victoryPointRewards").isJsonNull()) {
        JsonArray jsonArrayvictoryPointRewards = jsonObj.getAsJsonArray("victoryPointRewards");
        if (jsonArrayvictoryPointRewards != null) {
          // ensure the json data is an array
          if (!jsonObj.get("victoryPointRewards").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `victoryPointRewards` to be an array in the JSON string but got `%s`", jsonObj.get("victoryPointRewards").toString()));
          }

          // validate the optional field `victoryPointRewards` (array)
          for (int i = 0; i < jsonArrayvictoryPointRewards.size(); i++) {
            TerritoryRewardBracket.validateJsonElement(jsonArrayvictoryPointRewards.get(i));
          };
        }
      }
      // validate the optional field `zoneDefinition`
      if (jsonObj.get("zoneDefinition") != null && !jsonObj.get("zoneDefinition").isJsonNull()) {
        TerritoryZoneDefinition.validateJsonElement(jsonObj.get("zoneDefinition"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TerritoryTournamentConflictZoneDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TerritoryTournamentConflictZoneDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TerritoryTournamentConflictZoneDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TerritoryTournamentConflictZoneDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<TerritoryTournamentConflictZoneDefinition>() {
           @Override
           public void write(JsonWriter out, TerritoryTournamentConflictZoneDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TerritoryTournamentConflictZoneDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TerritoryTournamentConflictZoneDefinition given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TerritoryTournamentConflictZoneDefinition
   * @throws IOException if the JSON string is invalid with respect to TerritoryTournamentConflictZoneDefinition
   */
  public static TerritoryTournamentConflictZoneDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TerritoryTournamentConflictZoneDefinition.class);
  }

  /**
   * Convert an instance of TerritoryTournamentConflictZoneDefinition to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

