/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.doenisf.comlink4j.JSON;

/**
 * TerritoryPlayerUnitStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-05T21:53:04.897531600+02:00[Europe/Berlin]", comments = "Generator version: 7.8.0")
public class TerritoryPlayerUnitStatus {
  public static final String SERIALIZED_NAME_UNIT_ID = "unitId";
  @SerializedName(SERIALIZED_NAME_UNIT_ID)
  private String unitId;

  public static final String SERIALIZED_NAME_DEPLOYED_ZONE_ID = "deployedZoneId";
  @SerializedName(SERIALIZED_NAME_DEPLOYED_ZONE_ID)
  private String deployedZoneId;

  public TerritoryPlayerUnitStatus() {
  }

  public TerritoryPlayerUnitStatus unitId(String unitId) {
    this.unitId = unitId;
    return this;
  }

  /**
   * Get unitId
   * @return unitId
   */
  @javax.annotation.Nullable
  public String getUnitId() {
    return unitId;
  }

  public void setUnitId(String unitId) {
    this.unitId = unitId;
  }


  public TerritoryPlayerUnitStatus deployedZoneId(String deployedZoneId) {
    this.deployedZoneId = deployedZoneId;
    return this;
  }

  /**
   * Get deployedZoneId
   * @return deployedZoneId
   */
  @javax.annotation.Nullable
  public String getDeployedZoneId() {
    return deployedZoneId;
  }

  public void setDeployedZoneId(String deployedZoneId) {
    this.deployedZoneId = deployedZoneId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerritoryPlayerUnitStatus territoryPlayerUnitStatus = (TerritoryPlayerUnitStatus) o;
    return Objects.equals(this.unitId, territoryPlayerUnitStatus.unitId) &&
        Objects.equals(this.deployedZoneId, territoryPlayerUnitStatus.deployedZoneId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitId, deployedZoneId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerritoryPlayerUnitStatus {\n");
    sb.append("    unitId: ").append(toIndentedString(unitId)).append("\n");
    sb.append("    deployedZoneId: ").append(toIndentedString(deployedZoneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("unitId");
    openapiFields.add("deployedZoneId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TerritoryPlayerUnitStatus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TerritoryPlayerUnitStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TerritoryPlayerUnitStatus is not found in the empty JSON string", TerritoryPlayerUnitStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TerritoryPlayerUnitStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TerritoryPlayerUnitStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("unitId") != null && !jsonObj.get("unitId").isJsonNull()) && !jsonObj.get("unitId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unitId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unitId").toString()));
      }
      if ((jsonObj.get("deployedZoneId") != null && !jsonObj.get("deployedZoneId").isJsonNull()) && !jsonObj.get("deployedZoneId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deployedZoneId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deployedZoneId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TerritoryPlayerUnitStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TerritoryPlayerUnitStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TerritoryPlayerUnitStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TerritoryPlayerUnitStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<TerritoryPlayerUnitStatus>() {
           @Override
           public void write(JsonWriter out, TerritoryPlayerUnitStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TerritoryPlayerUnitStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TerritoryPlayerUnitStatus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TerritoryPlayerUnitStatus
   * @throws IOException if the JSON string is invalid with respect to TerritoryPlayerUnitStatus
   */
  public static TerritoryPlayerUnitStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TerritoryPlayerUnitStatus.class);
  }

  /**
   * Convert an instance of TerritoryPlayerUnitStatus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

