/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.MissionGrantedAbility;
import io.github.doenisf.comlink4j.model.TargetedStat;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ArtifactDefinition
 */
public class ArtifactDefinitionTest {
    private final ArtifactDefinition model = new ArtifactDefinition();

    /**
     * Model tests for ArtifactDefinition
     */
    @Test
    public void testArtifactDefinition() {
        // TODO: test ArtifactDefinition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'powerLevel'
     */
    @Test
    public void powerLevelTest() {
        // TODO: test powerLevel
    }

    /**
     * Test the property 'grantedAbility'
     */
    @Test
    public void grantedAbilityTest() {
        // TODO: test grantedAbility
    }

    /**
     * Test the property 'nameKey'
     */
    @Test
    public void nameKeyTest() {
        // TODO: test nameKey
    }

    /**
     * Test the property 'descriptionKey'
     */
    @Test
    public void descriptionKeyTest() {
        // TODO: test descriptionKey
    }

    /**
     * Test the property 'texture'
     */
    @Test
    public void textureTest() {
        // TODO: test texture
    }

    /**
     * Test the property 'targetedStat'
     */
    @Test
    public void targetedStatTest() {
        // TODO: test targetedStat
    }

    /**
     * Test the property 'tierId'
     */
    @Test
    public void tierIdTest() {
        // TODO: test tierId
    }

}
