/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.GcActivityLevel;
import io.github.doenisf.comlink4j.model.MemoryLevel;
import io.github.doenisf.comlink4j.model.PerformanceLevel;
import io.github.doenisf.comlink4j.model.VfxAllocationLevel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClientQualityData
 */
public class ClientQualityDataTest {
    private final ClientQualityData model = new ClientQualityData();

    /**
     * Model tests for ClientQualityData
     */
    @Test
    public void testClientQualityData() {
        // TODO: test ClientQualityData
    }

    /**
     * Test the property 'performanceLevel'
     */
    @Test
    public void performanceLevelTest() {
        // TODO: test performanceLevel
    }

    /**
     * Test the property 'memoryLevel'
     */
    @Test
    public void memoryLevelTest() {
        // TODO: test memoryLevel
    }

    /**
     * Test the property 'gcActivityLevel'
     */
    @Test
    public void gcActivityLevelTest() {
        // TODO: test gcActivityLevel
    }

    /**
     * Test the property 'vfxAllocationLevel'
     */
    @Test
    public void vfxAllocationLevelTest() {
        // TODO: test vfxAllocationLevel
    }

    /**
     * Test the property 'flag'
     */
    @Test
    public void flagTest() {
        // TODO: test flag
    }

}
