/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.DatacronSetMaterial;
import io.github.doenisf.comlink4j.model.DatacronSetTier;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatacronSet
 */
public class DatacronSetTest {
    private final DatacronSet model = new DatacronSet();

    /**
     * Model tests for DatacronSet
     */
    @Test
    public void testDatacronSet() {
        // TODO: test DatacronSet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'expirationTimeMs'
     */
    @Test
    public void expirationTimeMsTest() {
        // TODO: test expirationTimeMs
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'detailPrefab'
     */
    @Test
    public void detailPrefabTest() {
        // TODO: test detailPrefab
    }

    /**
     * Test the property 'setMaterial'
     */
    @Test
    public void setMaterialTest() {
        // TODO: test setMaterial
    }

}
