/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.CurrencyItem;
import io.github.doenisf.comlink4j.model.EquipmentType;
import io.github.doenisf.comlink4j.model.LookupActionLink;
import io.github.doenisf.comlink4j.model.LookupMission;
import io.github.doenisf.comlink4j.model.Rarity;
import io.github.doenisf.comlink4j.model.StatDef;
import io.github.doenisf.comlink4j.model.UnitTier;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EquipmentDef
 */
public class EquipmentDefTest {
    private final EquipmentDef model = new EquipmentDef();

    /**
     * Model tests for EquipmentDef
     */
    @Test
    public void testEquipmentDef() {
        // TODO: test EquipmentDef
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nameKey'
     */
    @Test
    public void nameKeyTest() {
        // TODO: test nameKey
    }

    /**
     * Test the property 'iconKey'
     */
    @Test
    public void iconKeyTest() {
        // TODO: test iconKey
    }

    /**
     * Test the property 'requiredLevel'
     */
    @Test
    public void requiredLevelTest() {
        // TODO: test requiredLevel
    }

    /**
     * Test the property 'equipmentStat'
     */
    @Test
    public void equipmentStatTest() {
        // TODO: test equipmentStat
    }

    /**
     * Test the property 'recipeId'
     */
    @Test
    public void recipeIdTest() {
        // TODO: test recipeId
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'sellValue'
     */
    @Test
    public void sellValueTest() {
        // TODO: test sellValue
    }

    /**
     * Test the property 'lookupMission'
     */
    @Test
    public void lookupMissionTest() {
        // TODO: test lookupMission
    }

    /**
     * Test the property 'mark'
     */
    @Test
    public void markTest() {
        // TODO: test mark
    }

    /**
     * Test the property 'obtainableTime'
     */
    @Test
    public void obtainableTimeTest() {
        // TODO: test obtainableTime
    }

    /**
     * Test the property 'raidLookup'
     */
    @Test
    public void raidLookupTest() {
        // TODO: test raidLookup
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'actionLinkLookup'
     */
    @Test
    public void actionLinkLookupTest() {
        // TODO: test actionLinkLookup
    }

    /**
     * Test the property 'requiredRarity'
     */
    @Test
    public void requiredRarityTest() {
        // TODO: test requiredRarity
    }

    /**
     * Test the property 'findFlowDisabled'
     */
    @Test
    public void findFlowDisabledTest() {
        // TODO: test findFlowDisabled
    }

    /**
     * Test the property 'raidImmediateLookup'
     */
    @Test
    public void raidImmediateLookupTest() {
        // TODO: test raidImmediateLookup
    }

}
