/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.GalacticBundleMainElementInventoryType;
import io.github.doenisf.comlink4j.model.GalacticBundleMainElementPage;
import io.github.doenisf.comlink4j.model.GalacticBundleMainElementType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GalacticBundleMainElement
 */
public class GalacticBundleMainElementTest {
    private final GalacticBundleMainElement model = new GalacticBundleMainElement();

    /**
     * Model tests for GalacticBundleMainElement
     */
    @Test
    public void testGalacticBundleMainElement() {
        // TODO: test GalacticBundleMainElement
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'elementType'
     */
    @Test
    public void elementTypeTest() {
        // TODO: test elementType
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'inventoryType'
     */
    @Test
    public void inventoryTypeTest() {
        // TODO: test inventoryType
    }

}
