/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetLocalizationBundle2XXResponseOneOf
 */
public class GetLocalizationBundle2XXResponseOneOfTest {
    private final GetLocalizationBundle2XXResponseOneOf model = new GetLocalizationBundle2XXResponseOneOf();

    /**
     * Model tests for GetLocalizationBundle2XXResponseOneOf
     */
    @Test
    public void testGetLocalizationBundle2XXResponseOneOf() {
        // TODO: test GetLocalizationBundle2XXResponseOneOf
    }

    /**
     * Test the property 'localizationBundle'
     */
    @Test
    public void localizationBundleTest() {
        // TODO: test localizationBundle
    }

}
