/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.CampaignElementIdentifier;
import io.github.doenisf.comlink4j.model.GuildRaidLockout;
import io.github.doenisf.comlink4j.model.GuildRaidSim;
import io.github.doenisf.comlink4j.model.SquadType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GuildRaid
 */
public class GuildRaidTest {
    private final GuildRaid model = new GuildRaid();

    /**
     * Model tests for GuildRaid
     */
    @Test
    public void testGuildRaid() {
        // TODO: test GuildRaid
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'nameKey'
     */
    @Test
    public void nameKeyTest() {
        // TODO: test nameKey
    }

    /**
     * Test the property 'summaryKey'
     */
    @Test
    public void summaryKeyTest() {
        // TODO: test summaryKey
    }

    /**
     * Test the property 'descKey'
     */
    @Test
    public void descKeyTest() {
        // TODO: test descKey
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'squadType'
     */
    @Test
    public void squadTypeTest() {
        // TODO: test squadType
    }

    /**
     * Test the property 'campaignElementIdentifier'
     */
    @Test
    public void campaignElementIdentifierTest() {
        // TODO: test campaignElementIdentifier
    }

    /**
     * Test the property 'iconPrefab'
     */
    @Test
    public void iconPrefabTest() {
        // TODO: test iconPrefab
    }

    /**
     * Test the property 'promotionKey'
     */
    @Test
    public void promotionKeyTest() {
        // TODO: test promotionKey
    }

    /**
     * Test the property 'portraitIcon'
     */
    @Test
    public void portraitIconTest() {
        // TODO: test portraitIcon
    }

    /**
     * Test the property 'raidSim'
     */
    @Test
    public void raidSimTest() {
        // TODO: test raidSim
    }

    /**
     * Test the property 'infoImage'
     */
    @Test
    public void infoImageTest() {
        // TODO: test infoImage
    }

    /**
     * Test the property 'lockout'
     */
    @Test
    public void lockoutTest() {
        // TODO: test lockout
    }

    /**
     * Test the property 'legacyRaid'
     */
    @Test
    public void legacyRaidTest() {
        // TODO: test legacyRaid
    }

    /**
     * Test the property 'currencyReward'
     */
    @Test
    public void currencyRewardTest() {
        // TODO: test currencyReward
    }

    /**
     * Test the property 'guildRewardsRequireAttempt'
     */
    @Test
    public void guildRewardsRequireAttemptTest() {
        // TODO: test guildRewardsRequireAttempt
    }

    /**
     * Test the property 'audioVictoryKey'
     */
    @Test
    public void audioVictoryKeyTest() {
        // TODO: test audioVictoryKey
    }

    /**
     * Test the property 'audioDefeatKey'
     */
    @Test
    public void audioDefeatKeyTest() {
        // TODO: test audioDefeatKey
    }

}
