/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.ActionLink;
import io.github.doenisf.comlink4j.model.Requirement;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecommendedSquad
 */
public class RecommendedSquadTest {
    private final RecommendedSquad model = new RecommendedSquad();

    /**
     * Model tests for RecommendedSquad
     */
    @Test
    public void testRecommendedSquad() {
        // TODO: test RecommendedSquad
    }

    /**
     * Test the property 'descriptionKey'
     */
    @Test
    public void descriptionKeyTest() {
        // TODO: test descriptionKey
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

    /**
     * Test the property 'unitDefId'
     */
    @Test
    public void unitDefIdTest() {
        // TODO: test unitDefId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'showRequirement'
     */
    @Test
    public void showRequirementTest() {
        // TODO: test showRequirement
    }

    /**
     * Test the property 'hideRequirement'
     */
    @Test
    public void hideRequirementTest() {
        // TODO: test hideRequirement
    }

    /**
     * Test the property 'actionLink'
     */
    @Test
    public void actionLinkTest() {
        // TODO: test actionLink
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
