/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RelicDefinition
 */
public class RelicDefinitionTest {
    private final RelicDefinition model = new RelicDefinition();

    /**
     * Model tests for RelicDefinition
     */
    @Test
    public void testRelicDefinition() {
        // TODO: test RelicDefinition
    }

    /**
     * Test the property 'relicTierDefinitionId'
     */
    @Test
    public void relicTierDefinitionIdTest() {
        // TODO: test relicTierDefinitionId
    }

    /**
     * Test the property 'upgradeTableId'
     */
    @Test
    public void upgradeTableIdTest() {
        // TODO: test upgradeTableId
    }

    /**
     * Test the property 'alignmentColorOverride'
     */
    @Test
    public void alignmentColorOverrideTest() {
        // TODO: test alignmentColorOverride
    }

    /**
     * Test the property 'texture'
     */
    @Test
    public void textureTest() {
        // TODO: test texture
    }

    /**
     * Test the property 'nameKey'
     */
    @Test
    public void nameKeyTest() {
        // TODO: test nameKey
    }

}
