/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.SeasonDivisionReference;
import io.github.doenisf.comlink4j.model.SeasonDivisionSkillBoundary;
import io.github.doenisf.comlink4j.model.SeasonLeagueReference;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SeasonDefinition
 */
public class SeasonDefinitionTest {
    private final SeasonDefinition model = new SeasonDefinition();

    /**
     * Model tests for SeasonDefinition
     */
    @Test
    public void testSeasonDefinition() {
        // TODO: test SeasonDefinition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nameKey'
     */
    @Test
    public void nameKeyTest() {
        // TODO: test nameKey
    }

    /**
     * Test the property 'seasonLeagueReference'
     */
    @Test
    public void seasonLeagueReferenceTest() {
        // TODO: test seasonLeagueReference
    }

    /**
     * Test the property 'seasonDivisionReference'
     */
    @Test
    public void seasonDivisionReferenceTest() {
        // TODO: test seasonDivisionReference
    }

    /**
     * Test the property 'seasonRewardTableId'
     */
    @Test
    public void seasonRewardTableIdTest() {
        // TODO: test seasonRewardTableId
    }

    /**
     * Test the property 'minimumBannerSeasonRewardThreshold'
     */
    @Test
    public void minimumBannerSeasonRewardThresholdTest() {
        // TODO: test minimumBannerSeasonRewardThreshold
    }

    /**
     * Test the property 'divisionSkillBoundary'
     */
    @Test
    public void divisionSkillBoundaryTest() {
        // TODO: test divisionSkillBoundary
    }

}
