/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.SocialStatusGuildBannerColor;
import io.github.doenisf.comlink4j.model.SocialStatusGuildBannerLogo;
import io.github.doenisf.comlink4j.model.SocialStatusIcon;
import io.github.doenisf.comlink4j.model.SocialStatusPortrait;
import io.github.doenisf.comlink4j.model.SocialStatusTitle;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SocialStatus
 */
public class SocialStatusTest {
    private final SocialStatus model = new SocialStatus();

    /**
     * Model tests for SocialStatus
     */
    @Test
    public void testSocialStatus() {
        // TODO: test SocialStatus
    }

    /**
     * Test the property 'chatIcons'
     */
    @Test
    public void chatIconsTest() {
        // TODO: test chatIcons
    }

    /**
     * Test the property 'chatTitles'
     */
    @Test
    public void chatTitlesTest() {
        // TODO: test chatTitles
    }

    /**
     * Test the property 'guildLogo'
     */
    @Test
    public void guildLogoTest() {
        // TODO: test guildLogo
    }

    /**
     * Test the property 'guildColor'
     */
    @Test
    public void guildColorTest() {
        // TODO: test guildColor
    }

    /**
     * Test the property 'chatPortraits'
     */
    @Test
    public void chatPortraitsTest() {
        // TODO: test chatPortraits
    }

}
