/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.BucketItem;
import io.github.doenisf.comlink4j.model.CampaignElementIdentifier;
import io.github.doenisf.comlink4j.model.CombatType;
import io.github.doenisf.comlink4j.model.TerritoryZoneDefinition;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TerritoryCovertZoneDefinition
 */
public class TerritoryCovertZoneDefinitionTest {
    private final TerritoryCovertZoneDefinition model = new TerritoryCovertZoneDefinition();

    /**
     * Model tests for TerritoryCovertZoneDefinition
     */
    @Test
    public void testTerritoryCovertZoneDefinition() {
        // TODO: test TerritoryCovertZoneDefinition
    }

    /**
     * Test the property 'zoneDefinition'
     */
    @Test
    public void zoneDefinitionTest() {
        // TODO: test zoneDefinition
    }

    /**
     * Test the property 'campaignElementIdentifier'
     */
    @Test
    public void campaignElementIdentifierTest() {
        // TODO: test campaignElementIdentifier
    }

    /**
     * Test the property 'victoryReward'
     */
    @Test
    public void victoryRewardTest() {
        // TODO: test victoryReward
    }

    /**
     * Test the property 'disableRewardOnMap'
     */
    @Test
    public void disableRewardOnMapTest() {
        // TODO: test disableRewardOnMap
    }

    /**
     * Test the property 'combatType'
     */
    @Test
    public void combatTypeTest() {
        // TODO: test combatType
    }

}
