/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.TerritoryBattlePlayerStatus;
import io.github.doenisf.comlink4j.model.TerritoryConflictZoneStatus;
import io.github.doenisf.comlink4j.model.TerritoryCovertZoneStatus;
import io.github.doenisf.comlink4j.model.TerritoryMapStat;
import io.github.doenisf.comlink4j.model.TerritoryReconZoneStatus;
import io.github.doenisf.comlink4j.model.TerritoryStrikeZoneStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TerritoryBattleStatus
 */
public class TerritoryBattleStatusTest {
    private final TerritoryBattleStatus model = new TerritoryBattleStatus();

    /**
     * Model tests for TerritoryBattleStatus
     */
    @Test
    public void testTerritoryBattleStatus() {
        // TODO: test TerritoryBattleStatus
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'definitionId'
     */
    @Test
    public void definitionIdTest() {
        // TODO: test definitionId
    }

    /**
     * Test the property 'conflictZoneStatus'
     */
    @Test
    public void conflictZoneStatusTest() {
        // TODO: test conflictZoneStatus
    }

    /**
     * Test the property 'strikeZoneStatus'
     */
    @Test
    public void strikeZoneStatusTest() {
        // TODO: test strikeZoneStatus
    }

    /**
     * Test the property 'reconZoneStatus'
     */
    @Test
    public void reconZoneStatusTest() {
        // TODO: test reconZoneStatus
    }

    /**
     * Test the property 'playerStatus'
     */
    @Test
    public void playerStatusTest() {
        // TODO: test playerStatus
    }

    /**
     * Test the property 'currentRound'
     */
    @Test
    public void currentRoundTest() {
        // TODO: test currentRound
    }

    /**
     * Test the property 'currentRoundEndTime'
     */
    @Test
    public void currentRoundEndTimeTest() {
        // TODO: test currentRoundEndTime
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'covertZoneStatus'
     */
    @Test
    public void covertZoneStatusTest() {
        // TODO: test covertZoneStatus
    }

    /**
     * Test the property 'currentStat'
     */
    @Test
    public void currentStatTest() {
        // TODO: test currentStat
    }

    /**
     * Test the property 'lastCommandNotificationTime'
     */
    @Test
    public void lastCommandNotificationTimeTest() {
        // TODO: test lastCommandNotificationTime
    }

    /**
     * Test the property 'mapCompletedEarly'
     */
    @Test
    public void mapCompletedEarlyTest() {
        // TODO: test mapCompletedEarly
    }

    /**
     * Test the property 'selected'
     */
    @Test
    public void selectedTest() {
        // TODO: test selected
    }

}
