/*
 * swgoh-comlink
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * The version of the OpenAPI document: 0.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.doenisf.comlink4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.doenisf.comlink4j.model.TerritoryGuildProfile;
import io.github.doenisf.comlink4j.model.TerritoryReconZoneStatus;
import io.github.doenisf.comlink4j.model.TerritoryWarConflictZoneStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TerritoryWarGuildStatus
 */
public class TerritoryWarGuildStatusTest {
    private final TerritoryWarGuildStatus model = new TerritoryWarGuildStatus();

    /**
     * Model tests for TerritoryWarGuildStatus
     */
    @Test
    public void testTerritoryWarGuildStatus() {
        // TODO: test TerritoryWarGuildStatus
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'conflictStatus'
     */
    @Test
    public void conflictStatusTest() {
        // TODO: test conflictStatus
    }

    /**
     * Test the property 'reconStatus'
     */
    @Test
    public void reconStatusTest() {
        // TODO: test reconStatus
    }

}
