package io.github.doenisf.comlink4j.model.gamedata;

import io.github.doenisf.comlink4j.model.gamedata.ability.Ability;
import io.github.doenisf.comlink4j.model.gamedata.ability.AbilityDecisionTree;
import io.github.doenisf.comlink4j.model.gamedata.misc.DailyActionCap;
import io.github.doenisf.comlink4j.model.gamedata.bundle.GalacticBundle;
import io.github.doenisf.comlink4j.model.gamedata.campaign.Campaign;
import io.github.doenisf.comlink4j.model.gamedata.misc.category.Category;
import io.github.doenisf.comlink4j.model.gamedata.challenge.Challenge;
import io.github.doenisf.comlink4j.model.gamedata.challenge.ChallengeStyle;
import io.github.doenisf.comlink4j.model.gamedata.configuration.GuildRaidConfig;
import io.github.doenisf.comlink4j.model.gamedata.configuration.GuildRaidGlobalConfig;
import io.github.doenisf.comlink4j.model.gamedata.configuration.SaveSquadConfig;
import io.github.doenisf.comlink4j.model.gamedata.configuration.TimeZoneChangeConfig;
import io.github.doenisf.comlink4j.model.gamedata.conquest.ConquestMission;
import io.github.doenisf.comlink4j.model.gamedata.misc.ConsumableType;
import io.github.doenisf.comlink4j.model.gamedata.misc.conversion.ConversionSet;
import io.github.doenisf.comlink4j.model.gamedata.misc.Cooldown;
import io.github.doenisf.comlink4j.model.gamedata.datacron.DatacronAffixTemplateSet;
import io.github.doenisf.comlink4j.model.gamedata.datacron.DatacronHelpEntry;
import io.github.doenisf.comlink4j.model.gamedata.datacron.DatacronSet;
import io.github.doenisf.comlink4j.model.gamedata.datacron.DatacronTemplate;
import io.github.doenisf.comlink4j.model.gamedata.definition.*;
import io.github.doenisf.comlink4j.model.gamedata.effect.Effect;
import io.github.doenisf.comlink4j.model.gamedata.effect.EffectTarget;
import io.github.doenisf.comlink4j.model.gamedata.environment.BattleEnvironment;
import io.github.doenisf.comlink4j.model.gamedata.environment.EnvironmentCollection;
import io.github.doenisf.comlink4j.model.gamedata.misc.event.EventBonus;
import io.github.doenisf.comlink4j.model.gamedata.misc.event.EventSampling;
import io.github.doenisf.comlink4j.model.gamedata.guild.GuildRaid;
import io.github.doenisf.comlink4j.model.gamedata.misc.help.HelpEntry;
import io.github.doenisf.comlink4j.model.gamedata.item.GuildExchangeItem;
import io.github.doenisf.comlink4j.model.gamedata.item.LinkedStoreItem;
import io.github.doenisf.comlink4j.model.gamedata.mod.ModRecommendation;
import io.github.doenisf.comlink4j.model.gamedata.misc.PowerUpBundle;
import io.github.doenisf.comlink4j.model.gamedata.misc.Recipe;
import io.github.doenisf.comlink4j.model.gamedata.misc.Requirement;
import io.github.doenisf.comlink4j.model.gamedata.reward.SeasonRewardTable;
import io.github.doenisf.comlink4j.model.gamedata.social.SocialStatus;
import io.github.doenisf.comlink4j.model.gamedata.squad.RecommendedSquad;
import io.github.doenisf.comlink4j.model.gamedata.stat.StatProgression;
import io.github.doenisf.comlink4j.model.gamedata.misc.table.Table;
import io.github.doenisf.comlink4j.model.gamedata.misc.targeting.TargetingSet;
import io.github.doenisf.comlink4j.model.gamedata.territory.TerritoryTournamentDailyRewardTable;
import io.github.doenisf.comlink4j.model.gamedata.unit.UnitDefPreview;
import io.github.doenisf.comlink4j.model.gamedata.unit.UnitGuideLayout;
import io.github.doenisf.comlink4j.model.gamedata.misc.PersistentVfx;
import io.github.doenisf.comlink4j.model.gamedata.misc.xptable.XpTable;
import lombok.Getter;

import java.util.List;

@Getter
public class GameData {
    private List<UnitDef> units;
    private List<BattleEnvironment> battleEnvironments;
    private List<XpTable> xpTable;
    private List<CraftingMaterialDef> material;
    private List<Recipe> recipe;
    private List<StatProgression> statProgression;
    private List<Category> category;
    private List<HelpEntry> helpEntry;
    private List<Challenge> challenge;
    private List<SkillDefinition> skill;
    private List<EventSampling> eventSampling;
    private List<EquipmentDef> equipmentDef;
    private List<WarDef> warDefinition;
    private List<TargetingSet> targetingSet;
    private List<Ability> ability;
    private List<Effect> effect;
    private List<Requirement> requirement;
    private List<PowerUpBundle> powerUpBundle;
    private List<GuildBannerDef> guildBannerDef;
    private List<GuildRaidConfig> raidConfig;
    private List<GuildRaid> guildRaid;
    private List<StatModSetDefinition> statModSet;
    private List<StatModDefinition> statMod;
    private List<GuildExchangeItem> guildExchangeItem;
    private List<Table> table;
    private List<UnlockAnnouncementDefinition> unlockAnnouncementDefinition;
    private List<EffectTarget> battleTargetingRule;
    private List<TerritoryBattleDefinition> territoryBattleDefinition;
    private List<TerritoryWarDefinition> territoryWarDefinition;
    private List<EnvironmentCollection> environmentCollection;
    private List<ChallengeStyle> challengeStyle;
    private SocialStatus socialStatus;
    private List<StarterGuildDef> starterGuild;
    private List<PlayerTitleDefinition> playerTitle;
    private List<ModRecommendation> modRecommendation;
    private List<PersistentVfx> persistentVfx;
    private List<TerritoryTournamentDefinition> territoryTournamentDefinition;
    private List<EventBonus> eventBonus;
    private List<SeasonDefinition> seasonDefinition;
    private List<PlayerPortraitDefinition> playerPortrait;
    private TimeZoneChangeConfig timeZoneChangeConfig;
    private List<String> effectIconPriority;
    private List<MysteryBoxDefinition> mysteryBox;
    private List<MysteryStatModDefinition> mysteryStatMod;
    private List<Cooldown> cooldown;
    private List<DailyActionCap> dailyActionCap;
    private List<EnergyRewardDefinition> energyReward;
    private String territoryTournamentMatchmakingDescKey;
    private List<SeasonLeagueDefinition> seasonLeagueDefinition;
    private List<SeasonDivisionDefinition> seasonDivisionDefinition;
    private List<SeasonRewardTable> seasonRewardTable;
    private List<RelicTierDefinition> relicTierDefinition;
    private List<ConversionSet> scavengerConversionSet;
    private List<UnitGuideDefinition> unitGuideDefinition;
    private List<GalacticBundle> galacticBundle;
    private List<LinkedStoreItem> linkedStoreItem;
    private List<TerritoryTournamentLeagueDefinition> territoryTournamentLeagueDefinition;
    private List<TerritoryTournamentDivisionDefinition> territoryTournamentDivisionDefinition;
    private List<SaveSquadConfig> saveSquadConfig;
    private GuildRaidGlobalConfig guildRaidGlobalConfig;
    private List<Campaign> campaign;
    private List<ConquestDefinition> conquestDefinition;
    private List<ConquestMission> conquestMission;
    private List<ArtifactDefinition> artifactDefinition;
    private List<AbilityDecisionTree> abilityDecisionTree;
    private List<ConsumableDefinition> consumableDefinition;
    private List<ConsumableType> consumableType;
    private List<ArtifactTierDefinition> artifactTierDefinition;
    private List<ConsumableTierDefinition> consumableTierDefinition;
    private List<RecommendedSquad> recommendedSquad;
    private List<UnitGuideLayout> unitGuideLayout;
    private List<DailyLoginRewardDefinition> dailyLoginRewardDefinition;
    private List<CalendarCategoryDefinition> calendarCategoryDefinition;
    private TerritoryTournamentDailyRewardTable territoryTournamentDailyRewardTable;
    private List<DatacronSet> datacronSet;
    private List<DatacronTemplate> datacronTemplate;
    private List<DatacronAffixTemplateSet> datacronAffixTemplateSet;
    private List<DatacronHelpEntry> datacronHelpEntry;
    private List<UnitDefPreview> displayableEnemy;
}
